name: microbiome
channels:
  - anaconda
  - defaults
dependencies:
  #- python=3.7.0
  - _py-xgboost-mutex=2.0=cpu_0
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20
  - cycler=0.10.0
  - icu=58.2
  - jpeg=9b
  - kiwisolver=1.2.0
  - libpng=1.6.37
  - libxgboost=0.90
  - matplotlib=2.2.2
  - openssl=1.1.1h
  - py-xgboost=0.90
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.6.7
  - seaborn=0.11.0
  - sip=4.19.24
  - sqlite=3.33.0
  - zlib=1.2.11
  - backcall=0.2.0
  - blas=1.0=mkl
  - colorama=0.4.4
  - decorator=4.4.2
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - joblib=0.17.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - libsodium=1.0.18
  - mkl=2020.2=256
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - pandas=1.1.3
  - parso=0.7.0
  - pickleshare=0.7.5
  - pip=20.2.3
  - prompt-toolkit=3.0.8
  - pygments=2.7.1
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyzmq=19.0.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=50.3.0
  - six=1.15.0
  - threadpoolctl=2.1.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - wheel=0.35.1
  - zeromq=4.3.2
  - jupyter
  - pip:
    - dash-bootstrap-components
    - dash-html-components==0.13.2
    - dash-core-components==0.38.1
    - dash
    - dash-renderer==0.15.1
    - dash-table==3.1.7
    - dash-uploader
    - plotly
    - flask-caching
    - catboost
    - statsmodels
    - scikit-bio
    - shap

